### ISSUE TITLE
不具合と思われる挙動について

### ISSUE THREAD

**Issue by gyohk** [nyatla/NyARToolkit-for-Processing#1]
ライブラリの動作を確認していて、2点ほど不具合ではないかと思う点がありました。
なお、processing 2.2.1 でサンプルコードを実行しています。

1.
master リポジトリに、lib/NyAR4psg.jar が含まれていないようです。

2.
以下のようなコードを実行すると、java.lang.AssertionError が発生します。

```
img = loadImage("photo.jpg");

nya = new MultiMarker(this, width, height, "camera_para.dat", NyAR4PsgConfig.CONFIG_PSG);
nya.addARMarker("patt.hiro", 80);
nya.detect(img);
```

お時間あるときにご確認いただければと思います。
よろしくお願いします。

**Comment by nyatla** [comment]
gyohkさん

ご報告有難うございます。
1.lib/NyAR4psg.jarについて
masterリポジトリにlibにファイルが無いのは正常です。
このフォルダには、パッケージを構成したときに同梱する外部jarファイルが配置されています。
パッケージを生成するには、resources/build.xmlにあるantスクリプトを実行してください。

2.AssertionErrorについて
ウインドウのwidth,heightと、ロードしたimgのサイズが一致しないのではないかと思います。
widthとheightにimgのサイズを指定してみてください。
アサートが出ている場合は、その文面を教えて下さい。

宜しくお願いします。

**Comment by gyohk** [comment]
ご回答ありがとうございます。
後ほど試してみます。
色々とこちらの知識が足りておらず、申し訳ありません。

**Comment by gyohk** [comment]
試してみたところ、正常に動作しました。
詳しくご回答いただきありがとうございました。
