### ISSUE TITLE
Processing jar missing?

### ISSUE THREAD

**Issue by MoritzSkowronski** [nyatla/NyARToolkit-for-Processing#2]
Hey,

I'm probably missing something, but is the .jar for processing missing? Or does one have to build it themselves? If so, could you provide me with a short guideline?

Cheers and thanks for the amazing library
Moritz

**Comment by nyatla** [comment]
Hi,
Source code repositry has not jar file.
It is build tree.

You can get completed package form releases/nyar4psg-2.1.0.zip
https://github.com/nyatla/NyARToolkit-for-Processing/releases/download/v2.1.0/nyar4psg-2.1.0.zip

![default](https://cloud.githubusercontent.com/assets/2483108/9921422/86582770-5d18-11e5-8acc-48490619682d.png)

It includes required jar files.

If you want to create a package from the source code, please run a script at resources/build.xml.
This is based on processing-library-template.

**Comment by MoritzSkowronski** [comment]
Thank you!
