### ISSUE TITLE
nya.drawBackground faulty

### ISSUE THREAD

**Issue by MoritzSkowronski** [nyatla/NyARToolkit-for-Processing#3]
Hey, 

it seems to me as though the drawBackground method is faulty. It draws the captured image outside of the window or to be more exact: It draws the window into the lower left quarter of the screen. Marker tracking still works fine though

**Comment by nyatla** [comment]
For this issue, there are several possible causes.
- camera device problems  - Check whether the camera device captures the image correctly.  Check whether the image in the image(cam,0,0) is drawn correctly.
- parameters mismatch - width and height of size(width,height) and MultiMarker(this,width,height,... and Capture(this,width,height) must be same size parameter. In rare case, Capture might be ignore the size parameters.
- version of the problem - Please tell me the Processing of versions and OS that was operating the NyARToolKit. If you possible, attach screenshot.

**Comment by MoritzSkowronski** [comment]
Hey, the camera works fine, I've tested it on both my laptops webcam and a kinect2 resulting in the same issue. 

I just tested it with the standard imagePickup Example using those setup values:

  size(640,480,P3D);
  colorMode(RGB, 100);
  println(MultiMarker.VERSION);
  cam=new Capture(this,640,480);
  nya=new MultiMarker(this,640,480,"camera_para.dat",NyAR4PsgConfig.CONFIG_PSG);
  nya.addARMarker("patt.hiro",80);//id=0
  cam.start();

Proccesing version is 3.0b5 and OS is Mac OS X Yosemite as well as Windows 8.1

![imagepickup](https://cloud.githubusercontent.com/assets/12486612/10130608/431d44f8-65ca-11e5-913e-f872895476f5.jpg)

**Comment by nyatla** [comment]
This bug is caused by the difference of ortho function behavior in Processing3.x and 2.x.
(I think it is bug of processing 2.x.)
Until making the patch, please cut&paste the next function call instead of nya.background().

``` java
void drawBackground2(PImage i_img)
{
  PMatrix3D mv=new PMatrix3D();
  mv.reset();
  mv.translate(0,0,-nya.FRUSTUM_DEFAULT_FAR_CLIP);
  PGraphicsOpenGL pgl=((PGraphicsOpenGL)g);
  pgl.pushProjection();
  pushMatrix();
//  ortho(0,i_img.width,0,i_img.height,nya.FRUSTUM_DEFAULT_NEAR_CLIP,nya.FRUSTUM_DEFAULT_FAR_CLIP+1);//2.x
  ortho(-i_img.width/2,i_img.width/2,-i_img.height/2,i_img.height/2,nya.FRUSTUM_DEFAULT_NEAR_CLIP,nya.FRUSTUM_DEFAULT_FAR_CLIP+1);//3/x
  setMatrix(mv);
  image(i_img,-i_img.width/2,-i_img.height/2);
  popMatrix();
  pgl.popProjection();
}
```

Sketch Example

``` java
void setup() {
:
}

//copy the path function here
void drawBackground2(PImage i_img)
{
:
}
void draw()
{
:
  nya.detect(img);
  background(0);
  drawBackground2(img); //new function
//  nya.drawBackground(img);//frustumを考慮した背景描画 //comment out
  for(int i=0;i<4;i++){
:
}
```

**Comment by MoritzSkowronski** [comment]
works perfectly, thank you!
