### ISSUE TITLE
Camera frozen

### ISSUE THREAD

**Issue by monicadefran** [nyatla/NyARToolkit-for-Processing#4]
Hi,

When I run the pngMarker script, the camera seems to take the first frame and stays frozen. I am using Processing 3.0.2 with nyar4psg-2.1.0. in  a Windows 8.1 64-bit. Could someone help me with the problem or give any clue. The code is below:

/**
  NyARToolkit for proce55ing/1.2.0
  (c)2008-2012 nyatla
  airmail(at)ebony.plala.or.jp

  This sample program uses a PNG image instead of the patt file.
  The PNG image must be square form that includes edge.
*/

import processing.video._;
import jp.nyatla.nyar4psg._;

Capture cam;
MultiMarker nya;

void setup() {
  size(640,480,P3D);
  colorMode(RGB, 100);
  println(MultiMarker.VERSION);
  cam = new Capture(this, 640, 480);
  nya = new MultiMarker(this ,width ,height ,"camera_para.dat",NyAR4PsgConfig.CONFIG_PSG);
  nya.addARMarker(loadImage("marker.png"),16,25,80);
  cam.start();
}

void drawBackground2(PImage i_img)
{
  PMatrix3D mv=new PMatrix3D();
  mv.reset();
  mv.translate(0,0,-nya.FRUSTUM_DEFAULT_FAR_CLIP);
  PGraphicsOpenGL pgl=((PGraphicsOpenGL)g);
  pgl.pushProjection();
  pushMatrix();
//  ortho(0,i_img.width,0,i_img.height,nya.FRUSTUM_DEFAULT_NEAR_CLIP,nya.FRUSTUM_DEFAULT_FAR_CLIP+1);//2.x
  ortho(-i_img.width/2,i_img.width/2,-i_img.height/2,i_img.height/2,nya.FRUSTUM_DEFAULT_NEAR_CLIP,nya.FRUSTUM_DEFAULT_FAR_CLIP+1);//3/x
  setMatrix(mv);
  image(i_img,-i_img.width/2,-i_img.height/2);
  popMatrix();
  pgl.popProjection();
}

void draw()
{
  if (cam.available() !=true) {
      return;
  }
  cam.read();
  nya.detect(cam);
  background(0);
  drawBackground2(cam); //new function
//  nya.drawBackground(cam);//frustumを考慮した背景描画//comment out
  if((!nya.isExistMarker(0))){
    return;
  }

  nya.beginTransform(0);
  fill(0,0,255);
  translate(0,0,20);
  box(40);
  nya.endTransform();
}

**Comment by nyatla** [comment]
Hello.
This issue has been reproduced in 3.0.2.
Please wait because  I am looking for measures.

**Comment by nyatla** [comment]
I could not specifie the reason of problem. However the problem can be avoided by to insert the following code.
![image](https://cloud.githubusercontent.com/assets/2483108/14372535/8a2ac47a-fd7c-11e5-8e0f-0d31af4f5ed9.png)

Please insert "cam.updatePixels();" into after cam.read();

**Comment by monicadefran** [comment]
YYeehhhaaa, it works perfect! Thank you for the solution nyatla.

**Comment by nyatla** [comment]
I fixed the issue by 3.0.2.
The patch is not required.
