### ISSUE TITLE
Android Mode, can not specify "camera_para.dat" and marker files properly

### ISSUE THREAD

**Issue by ghost** [nyatla/NyARToolkit-for-Processing#5]
Hi, i'm currently trying to get NyARToolkit-for-Processing on Android Mode and i'm running into some issues, which i think could be sorted. 

Specifically, i'm having trouble when trying to initialize the MultiMarker object on this line:

`nya=new MultiMarker(this,width,height, "camera_para.dat" ,NyAR4PsgConfig.CONFIG_PSG);`

Apparently Android does not have a /data folder so it does not find any file. I've tried using absolute paths such as "/storage/emulated/0/Download/camera_para.dat" but that does not work either.

I've traced the error down to this (see this [SO](http://stackoverflow.com/questions/27053487/illegalargumentexception-file-contains-a-path-separator-android)): Looks like PApplet class calls the createInput method with the filename string as a parameter, but for some reason it does not accept "separators".

```
public MultiMarker(PApplet i_applet, int i_width,int i_height,String i_cparam_file,NyAR4PsgConfig i_config)

{

     this(i_applet,new SingleCameraView(i_applet,   NyARParam.loadFromARParamFile(i_applet.createInput(i_cparam_file), i_width, i_height),i_config._ps_patch_version), i_config);       
     return;
}

```

createInput on PApplet has an overload that accepts a File object as input, so if this overload were added i think this issue would be solved (see that i_cparam_file is File object now):

```
public MultiMarker(PApplet i_applet, int i_width,int i_height,File i_cparam_file,NyAR4PsgConfig i_config)

{

     this(i_applet,new SingleCameraView(i_applet,   NyARParam.loadFromARParamFile(i_applet.createInput(i_cparam_file), i_width, i_height),i_config._ps_patch_version), i_config);       
     return;
}

```

If someone knows any way of solving this without doing this modification please let me know.

**Comment by nyatla** [comment]
Thank you for report.
It is very nice.
I add an API that has the InputStream argument.
This problem is exist also in other functions that take file name argument.
I will add functions to other functions.

I add the API soon. Please wait a little.

**Comment by ghost** [comment]
Thank you! Awesome library!

**Comment by ghost** [comment]
Also, i think the same thing will happen with the addMarker methods:

`public int addARMarker(String i_file_name,int i_patt_resolution,int i_edge_percentage,float i_width)`

This method is also calling createInput with i_file_name as String, so i think the behaviour should be the same. The good news here is that i think that this could be avoided by using the overload that uses PImage that already exists: 

`public int addARMarker(PImage i_img,int i_patt_resolution,int i_edge_percentage,float i_width)`

But if you are already adding extra APIs then why not add one more :D

**Comment by nyatla** [comment]
I've added function with InputStream argument to all file IO function.

A new release can be downloaded from the following.
https://github.com/nyatla/NyARToolkit-for-Processing/releases

Please write the code as following.

```
new MultiNft(applet,width,height,applet.createInput(new File(filename)),config)
```

**Comment by ghost** [comment]
Thankyou @nyatla !!!
I have managed to get NyARToolkit library to work on my Android phone. Thanks again!

**Comment by vimal-b** [comment]
Will u post some sample code to test please..nyatla

**Comment by vimal-b** [comment]
I tried but app crashes
