### ISSUE TITLE
Could you add this library to the list showed in Processing IDE's "Library Manager"?

### ISSUE THREAD

**Issue by q2dg** [nyatla/NyARToolkit-for-Processing#6]
This would give a lot more visibility to this project.
Thanks!

**Comment by nyatla** [comment]
Hello.
Thank you for message.

Do your processing can be set up the NyARtoolkit for processing as follows?

I think that it can recognize to unzip zip file and copy in the library directory of the processing.

If you can not, Please let me know the processing version.
![default](https://cloud.githubusercontent.com/assets/2483108/17160190/2ecc45c8-53de-11e6-8355-ba98a10ed060.png)

**Comment by q2dg** [comment]
Well, no, sorry.
I've downloaded last zip from your github, I've decompressed and I've copied the resulting folder inside my Processing "libraries" folder. But nothing appears in Processing menu.I'm using last version, 3.1.1

Maybe these links help:

https://github.com/processing/processing/wiki/Library-Basics
https://github.com/processing/processing/wiki/Library-Guidelines
https://github.com/processing/processing/wiki/Library-Overview

PD: I've renamed decompressed folder so hyphens doesn't appear on it, just in case, but with no luck. I attach screenshot 
![captura de 2016-07-28 13-39-56](https://cloud.githubusercontent.com/assets/7274874/17211303/f5bc87b6-54c8-11e6-984f-c960143af531.png)

**Comment by nyatla** [comment]
Hi,
Would you change folder name to nyar4psg?
The library did not appear in case of another name.

**Comment by q2dg** [comment]
With this name doesn't appear neither, sorry

**Comment by nyatla** [comment]
I wonder to the your first directory name is "NyARToolkit".
It might  be Nyartoolkit for Java.
Do you download NyARtoolkit for processing below URL?

https://github.com/nyatla/NyARToolkit-for-Processing/releases

**Comment by q2dg** [comment]
Good news. 
Downloading 5.0.5pre version from link you provided it appears in Libraries menu as "nyar4psg" both when I don't change the name of descompressed zip (that is to say: when it remains "nyar4psg") as if I change it to NyARToolkit.  If the name is Nyartoolkit it doesn't appear, instead.

**Comment by nyatla** [comment]
I'm sorry for late reply.
The name of the library seems to be fixed by the package setting.
If there is no problem, please use remains the name of the "nyar4psg" .

**Comment by ffd8** [comment]
I second this request – faaaantastic library (thanks!) that took a few hours to find through older projects that weren't compiling. I also suggest publicizing the library within Processing Contribution Manager (ideally with a few keywords in the title, 'augmented', 'artoolkit', 'marker') so that one can quickly find it in the future: https://github.com/processing/processing/wiki/Library-Basics#advertising-your-library
